[build]
publish = "dist"
command = "pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--version"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
